apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-api
  namespace: exchange
  labels:
    app: exchange-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exchange-api
  template:
    metadata:
      labels:
        app: exchange-api
    spec:
      containers:
      - name: exchange-api
        image: exchange/api:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: websocket
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: exchange-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: exchange-secrets
              key: jwt-secret
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: SERVER_HOST
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: SERVER_PORT
        - name: JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: exchange-config
              key: JWT_EXPIRATION
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-api
  namespace: exchange
  labels:
    app: exchange-api
spec:
  selector:
    app: exchange-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: websocket
    port: 8081
    targetPort: 8081
  type: ClusterIP 