apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-config
  namespace: exchange
data:
  # Server configuration
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  
  # Database configuration
  DATABASE_MAX_CONNECTIONS: "10"
  DATABASE_MIN_CONNECTIONS: "2"
  
  # JWT configuration
  JWT_EXPIRATION: "86400"
  
  # CORS configuration
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  
  # Redis configuration
  REDIS_URL: "redis://redis:6379"
  
  # Frontend configuration
  VITE_API_BASE_URL: "http://localhost:8080" 