apiVersion: v1
kind: Secret
metadata:
  name: exchange-secrets
  namespace: exchange
type: Opaque
data:
  # Base64 encoded values (replace with actual values)
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9leGNoYW5nZQ==
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl
  redis-password: cmVkaXMtcGFzc3dvcmQ=
  postgres-user: dXNlcg==
  postgres-password: cGFzc3dvcmQ=
